[tool.poetry]
name = "cleanrlhf"
version = "0.1.0"
description = ""
authors = ["Benjamin Kuen <b.kuen@campus.lmu.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tensorboard = "^2.10.0"
wandb = "^0.13.11"
torch = ">=1.12.1"
gym = "0.23.1"
gymnasium = "0.28.1"
tyro = "^0.5.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
