[tool.poetry]
name = "cleanrlhf"
version = "0.1.0"
description = ""
authors = ["Benjamin Kuen <b.kuen@campus.lmu.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gym = "0.23.1"
gymnasium = ">=0.28.1"
imageio = "^2.14.1"
moviepy = "^1.0.3"
mujoco = "<=2.3.3"
opencv-python = "^4.10.0"
stable-baselines3 = "2.0.0"
tensorboard = "^2.10.0"
torch = ">=1.12.1"
tyro = "^0.5.10"
wandb = "^0.13.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
