python3 sac_rlhf.py --env-id=Ant-v4 \
  --num-envs=1 \
  --exp_name=Benjamin-Test \
  --wandb_project_name=Benjamin-Test \
  --track \
  --capture_video \
  --log_level=INFO \
  --total_timesteps=1000000 \
  --preference_sampling=disagree \
  --teacher-sim-delta-skip=-1e7 \
  --total_explore_steps=10000 \
  --unsupervised_exploration \
  --exploration-load \
  --path-to-replay-buffer=models/Ant-v4__Benjamin-Test__1__1736680754/10000/replay_buffer.pth \
  --path-to-model=models/Ant-v4__Benjamin-Test__1__1736680754/10000/checkpoint.pth