name: pre-commit

on:
  pull_request:
  push:
    branches: [main]


jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install pre-commit"
        run: pip install pre-commit
      - run: pre-commit run --all-files